Feat#16 게시물 기초적 도메인 구현
Leets-Official/Z-BE pull request #23
Opened 2024-10-09 14:54 UTC by 1winhyun

## 1. 무슨 이유로 코드를 변경했나요?
게시물 기초적 도메인 구현
<br>

## 2. 어떤 위험이나 장애를 발견했나요?

<br>

## 3. 관련 스크린샷을 첨부해주세요.

<br>

## 4. 완료 사항

<br>

## 5. 추가 사항

2024-10-09 15:25 UTC, soyesenna requested changes
고생하셨습니다!!
Post의 createdAt, updatedAt 부분만 수정해주시면 될 것 같아요!!

2024-10-09 15:25 UTC, soyesenna commented on src/main/java/com/leets/team2/xclone/domain/post/dto/PostDTO.java
> +    }
좋은 것 같습니다!!
다만, 제목이나 내용 같은 String 값은 길이도 validation을 하는 게 더 안정적인 것 같다고 생각해요!!
나중에 실제로 구현하실때 참고해주시면 감사하겠습니당🫡

2024-10-09 15:25 UTC, soyesenna commented on src/main/java/com/leets/team2/xclone/domain/post/entity/Post.java
> +    private LocalDateTime updatedAt;
이 부분은 AbstractEntity에 존재하는 필드여서 제거해도 될 것 같습니다!!

2024-10-09 15:26 UTC, 1winhyun commented on src/main/java/com/leets/team2/xclone/domain/post/entity/Post.java
> +    private LocalDateTime updatedAt;
넵 알겠습니다.

2024-10-09 15:26 UTC, 1winhyun commented on src/main/java/com/leets/team2/xclone/domain/post/dto/PostDTO.java
> +    }
실제 구현시 참고하겠습니다!!

2024-10-09 15:30 UTC, jj0526 requested changes
수고하셨습니다 몇몇 사항 수정 부탁드려요

2024-10-09 15:30 UTC, jj0526 commented on src/main/java/com/leets/team2/xclone/domain/post/dto/PostDTO.java
> +    //DTO 같은 경우 각각의 기능에 따른 DTO를 전부 만들 예정입니다. 다음은 예시 상황입니다. 이런 방식으로 구현하는건 어떻게 생각하시는지 의견 부탁드리겠습니다.
각각의 기능이라면 원본, 댓글, 공유인 경우를 모두 따로 만든다는건가요? 모두 같은 기능(댓글/공유/사진 첨부 등)을 하여서 하나로 만드는게 좋아보여요

2024-10-09 15:30 UTC, jj0526 commented on src/main/java/com/leets/team2/xclone/domain/post/dto/PostDTO.java
> +            Long postId,
반환할 때는 postId를 받지만 생성할 때에는 postId가 필요하지 않은거 같아요

2024-10-09 15:30 UTC, jj0526 commented on src/main/java/com/leets/team2/xclone/domain/post/entity/Post.java
> +    private LocalDateTime updatedAt;
createdAt은 이미 있어서 updatedAt만 남기고 글이 수정된 경우 업데이트 하는것도 좋아보여요!

2024-10-09 15:31 UTC, 1winhyun commented on src/main/java/com/leets/team2/xclone/domain/post/entity/Post.java
> +    private LocalDateTime updatedAt;
이 부분 수정했습니다.

2024-10-09 15:34 UTC, 1winhyun commented on src/main/java/com/leets/team2/xclone/domain/post/dto/PostDTO.java
> +            Long postId,
아 이부분은 원래 게시물이 어느 회원에 속해있는지 확인하려구 memberId를 추가하려 했었는데 postId도 잘못 작성된 것 같습니다. memberId를 넣는 것은 어떻게 생각하시나요?

2024-10-09 15:35 UTC, 1winhyun commented on src/main/java/com/leets/team2/xclone/domain/post/dto/PostDTO.java
> +    //DTO 같은 경우 각각의 기능에 따른 DTO를 전부 만들 예정입니다. 다음은 예시 상황입니다. 이런 방식으로 구현하는건 어떻게 생각하시는지 의견 부탁드리겠습니다.
예를 들면 createPostResponse/createPostRequest, updatePostResponse/updatePostRequest 이런식으로 만드려 했습니다. 어떻게 생각하시나요?

2024-10-09 15:54 UTC, jj0526 commented on src/main/java/com/leets/team2/xclone/domain/post/dto/PostDTO.java
> +            Long postId,
어차피 로그인한 유저의 정보가 없으니 memberId는 필요 없을거같아요

2024-10-09 16:02 UTC, jj0526 commented on src/main/java/com/leets/team2/xclone/domain/post/dto/PostDTO.java
> +    //DTO 같은 경우 각각의 기능에 따른 DTO를 전부 만들 예정입니다. 다음은 예시 상황입니다. 이런 방식으로 구현하는건 어떻게 생각하시는지 의견 부탁드리겠습니다.
Response와 Request는 나누고 create랑 update는 제목, 내용 들어가는게 똑같아서 안나눠도 될거같아요!

2024-10-10 04:18 UTC, 1winhyun commented on src/main/java/com/leets/team2/xclone/domain/post/dto/PostDTO.java
> +    //DTO 같은 경우 각각의 기능에 따른 DTO를 전부 만들 예정입니다. 다음은 예시 상황입니다. 이런 방식으로 구현하는건 어떻게 생각하시는지 의견 부탁드리겠습니다.
알겠습니다!! 현재는 예시 사항으로 작성해놓은거라 구현시 참고하겠습니다.

2024-10-10 04:20 UTC, 1winhyun commented on src/main/java/com/leets/team2/xclone/domain/post/dto/PostDTO.java
> +            Long postId,
이것도 이런식으로 구현하겠다 정도만 예시로 작성된거라 구현할 때 반영하겠습니다.

2024-10-10 05:50 UTC, merged