Feat#21 게시물 생성, 삭제, 수정 API 구현
Leets-Official/Z-BE pull request #26
Opened 2024-11-02 15:29 UTC by 1winhyun

## 1. 무슨 이유로 코드를 변경했나요?

<br> 게시물 생성, 삭제, 수정을 구현하였습니다. 아직 사진과 동영상을 올리는 것과 공유 관련 기능은 아직 구현되지 않았습니다. 먼저 이 부분에 대한 피드백을 받고 진행하겠습니다.

## 2. 어떤 위험이나 장애를 발견했나요?

<br>

## 3. 관련 스크린샷을 첨부해주세요.

<br>

## 4. 완료 사항

<br>

## 5. 추가 사항

2024-11-03 17:27 UTC, soyesenna requested changes
고생하셨습니다👍
리뷰 확인 부탁드립니다!!

2024-11-03 17:27 UTC, soyesenna commented on src/main/java/com/leets/team2/xclone/domain/post/controller/PostController.java
> +        Post post=postService.createPost(postDTO,author);
이런 비즈니스 로직은 Service layer로 분리하는게 좋아보입니다👍

2024-11-03 17:27 UTC, soyesenna commented on src/main/java/com/leets/team2/xclone/domain/post/controller/PostController.java
> +    }
DTO를 사용하기로 한 이상, 각각의 Request와 Response에 대해서 각각 다른 DTO를 사용하는게 좋습니다.
만약, 여러 컨트롤러가 같은 DTO를 사용하고있는 상황에서 하나의 컨트롤러의 변경으로 인해 DTO가 변경된다면 다른 컨트롤러까지 영향을 받으니까요🤔 같은 필드를 가진 DTO라고 하더라도 분리해서 사용하는건 어떠신가요?
(저는 개인적으로 DTO는 무한으로 복사되어도 상관 없다는 생각이긴 합니다...ㅎㅎ😅)

2024-11-04 04:06 UTC, jj0526 requested changes

2024-11-04 04:06 UTC, jj0526 commented on src/main/java/com/leets/team2/xclone/domain/post/controller/PostController.java
> +        postService.deletePost(postId);
여기서도 본인이 쓴 게시물인지 확인하는 로직도 필요해보여요

2024-11-04 04:06 UTC, jj0526 commented on src/main/java/com/leets/team2/xclone/domain/post/controller/PostController.java
> +        Post updatedPost=postService.updatePost(postId,postDTO);
본인이 쓴 게시물인지 확인하는 로직이 필요해 보여요

2024-11-04 07:16 UTC, 1winhyun commented on src/main/java/com/leets/team2/xclone/domain/post/controller/PostController.java
> +        postService.deletePost(postId);
구현했습니다. 확인한번 부탁드립니다.

2024-11-04 07:16 UTC, 1winhyun commented on src/main/java/com/leets/team2/xclone/domain/post/controller/PostController.java
> +        Post updatedPost=postService.updatePost(postId,postDTO);
구현했습니다. 확인 한번 부탁드립니다.

2024-11-04 09:03 UTC, 1winhyun commented on src/main/java/com/leets/team2/xclone/domain/post/controller/PostController.java
> +    }
수정하였습니다. 확인 한번 부탁드립니다.

2024-11-04 11:20 UTC, soyesenna approved these changes
고생하셨습니다!!

2024-11-06 06:47 UTC, jj0526 requested changes

2024-11-06 06:47 UTC, jj0526 commented on src/main/java/com/leets/team2/xclone/domain/comment/controller/CommentController.java
> +    @DeleteMapping("/{commentId}/delete")
/delete를 꼭 추가하지 않고 /{commentId}로만 해도 괜찮아보여요

2024-11-06 06:47 UTC, jj0526 commented on src/main/java/com/leets/team2/xclone/domain/comment/service/CommentService.java
> +
트랜잭션을 추가해서 데이터의 무결성을 유지하는게 좋아보여요!

2024-11-06 06:47 UTC, jj0526 commented on src/main/java/com/leets/team2/xclone/domain/comment/service/CommentService.java
> +
그리고 댓글 수정 기능도 필요해 보입니다

2024-11-06 06:47 UTC, jj0526 commented on src/main/java/com/leets/team2/xclone/domain/post/dto/PostResponseDTO.java
> +    private String imageUrl;//이미지 url
이미지를 여러개 올리기 위해 이미지는 따로 entity로 분리하는게 좋아보여요

2024-11-07 02:02 UTC, jj0526 requested changes

2024-11-07 02:02 UTC, jj0526 commented on src/main/java/com/leets/team2/xclone/domain/post/controller/PostController.java
> +    @PatchMapping("/{postId}/edit")
HTTP 메서드 자체가 어떤 동작을 수행하는지 보이기때문에 edit 등을 경로에 동작을 명시 안하는게 좋아보입니다

2024-11-07 02:02 UTC, jj0526 commented on src/main/java/com/leets/team2/xclone/domain/post/controller/PostController.java
> +    @DeleteMapping("/{postId}/delete")
여기서도 delete를 경로에 동작을 명시 안하는게 좋아보입니다

2024-11-07 02:02 UTC, jj0526 commented on src/main/java/com/leets/team2/xclone/domain/post/service/PostService.java
> +    public PostResponseDTO toPostResponseDTO(Post post){//자식 게시물 리스트를 DTO로 변환
PostResponseDTO에 구현하는게 좋아보입니다

2024-11-07 04:27 UTC, 1winhyun commented on src/main/java/com/leets/team2/xclone/domain/post/controller/PostController.java
> +    @DeleteMapping("/{postId}/delete")
아 그렇네요!! 어차피 DeleteMapping해서 없어도 될 것 같아요!! 삭제했습니다.

2024-11-07 04:27 UTC, 1winhyun commented on src/main/java/com/leets/team2/xclone/domain/post/controller/PostController.java
> +    @PatchMapping("/{postId}/edit")
삭제했습니다!!

2024-11-07 04:31 UTC, 1winhyun commented on src/main/java/com/leets/team2/xclone/domain/post/service/PostService.java
> +    public PostResponseDTO toPostResponseDTO(Post post){//자식 게시물 리스트를 DTO로 변환
제가 이 부분은 가장 중요한 게시물 서비스 내용이라고 해서 일부로 PostService안에 넣어놨습니다!!

2024-11-07 11:22 UTC, merged